# Fichier de configuration du site à personnaliser

# Informations du site 
site_name: NSI Terminale 2022-2023
site_description: Cours et TD de l'année en cours
site_author: "Michael Meyroneinc-condy" 
copyright: 2023 sous licence <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr" target="_blank">CC BY-NC-SA 4.0</a> 
site_url: 

# Structure des dossiers :
docs_dir: docs

# Menu de navigation
nav: 
    - Accueil : index.md
    #- Test : Notebook.ipynb

    - T1 - Struct. de données :
    #- T1 - Struct. de données :  StructureDonnees/T1_1_Recursivite.md
      - T1_1 P.O.O : StructureDonnees/T1_1_Programmation_Orientee_Objet.md
      - T1_2 POO Exercices : StructureDonnees/T1_2_TD_POO.md
      - T1_3 TD POO BAC : StructureDonnees/T1_3_BAC_Capytale.md     
      - T1_4 Sujet POO BAC : StructureDonnees/POO_BAC_correction.md
    
    - T2 - Bases de données :  
      - TP 01 Modèle relationnel : BasesDonnees/Modele_Relationnel.md
      - TP 02 Langage SQL : BasesDonnees/Cours_TP_SQL.md
      - BAC SQL : BasesDonnees/SQL_BAC.md
      - BAC SQL Correction : BasesDonnees/SQL_BAC_correction.md
    
    #- T3 - Archi. matèrielle :
    
    #- T4 - Programmation :
    #   - Récursivité : Programmation/T4_1_TP_Recursivite_correction.md

    #- T5 Algo. : 

    
    #- BAC 📝:

    
    - E.P 💻: 
      - Déroulement : epreuve_pratique.md
      - Consigne : divers/Consigne_EP.md
    #  - Sujets : divers/EpreuvePratique.md
      #- EP 2022 : BAC/EP_2022.md
  
    - Evaluations :
      - DS01 : Evaluations/BDD_Devoir.md



    - Divers :
      - Epreuve GEIPI : divers/sujet0_geipi.pdf
    - Divers conseils : divers/conseil.md

    


# Définition du thème https://squidfunk.github.io/mkdocs-material/creating-your-site/
theme:
    name: material
    custom_dir: overrides
    font: false  # RGPD ; pas de fonte Google
    language: fr # français
    icon:
      logo: fontawesome/solid/spider
    favicon : images/dragon.svg

    palette: # Palettes de couleurs jour/nuit, cf : https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
      - scheme: default # nom du thème clair
        primary: indigo # couleur primaire des titres, des liens, ..., à prendre dans la liste
        accent: indigo # couleur d'accentuation au survol des boutons, desliens, ..., à prendre dans la liste
        toggle: # définition du bouton pour switcher de palette
          icon: material/lightbulb # apparence
          name: Basculer en mode sombre # message
      - scheme: slate # nom du thème sombre
        primary: teal
        accent: teal
        toggle:
          icon: material/lightbulb-outline
          name: Basculer en mode clair

    features:
        - navigation.instant
        - navigation.tabs
        #- navigation.expand
        - navigation.top
        - navigation.sections
        - navigation.indexes
        - navigation.tracking
        #- toc.integrate
        - header.autohide
        - content.code.annotate
     


markdown_extensions: # https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
    # extensions de la bibliothèque markdown standard
    - abbr                          # infobulles sur abbréviations 
    - meta                          # Métadonnées
    - def_list                      # Les listes de définition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - md_in_html                    # Pour écrire en MarkDown dans des balises HTML https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorés  !!! info "ma remarque"
    - toc: # Table des matières
        permalink: ⚓︎
        toc_depth: 3
    # extensions de python-markdown https://facelessuser.github.io/pymdown-extensions/
    - pymdownx.details              #   qui peuvent se plier/déplier.
    - pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surligné==.
    - pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
    - pymdownx.highlight:            # Coloration syntaxique du code
        auto_title: true
        auto_title_map:
            "Python": "🐍 Script Python"
            "Python Console Session": "🐍 Console Python"
            "Text Only": "📋 Texte"
            "E-mail": "📥 Entrée"
            "Text Output": "📤 Sortie"
            "SQL": "🗂️ Requête SQL"

    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed:               # Volets glissants.  === "Mon volet"
        alternate_style: true 
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:  # Formules en LaTeX 
        generic: true



plugins:

  - search # Inclure une barre de recherche
  - mkdocs-jupyter: # Convertir les fichiers .ipynb et .py en pages du site https://github.com/danielfrg/mkdocs-jupyter
      kernel_name: python3
      execute: False
      include_source: True
  - macros
  - awesome-pages:
      collapse_single_pages: true


  - page-to-pdf : 
      disable: False
      disableOnServe: False
      displayHeaderFooter: True
      printBackground: True
      scale : 1.0
      landscape : False
      #margin: {'top': '0.75cm', 'bottom': '0.75cm', 'right': '0.5cm','left': '0.5cm'}
      headerTemplate: '<header style="width:100%;heigth:45px;font-size:10px;font-weight:600;color:white;background:#A19162;margin-top:-20px;padding:10px;padding-bottom:0;-webkit-print-color-adjust: exact">
                       <span style="display:inline-block;vertical-align:middle;margin-top:-4px;margin-left:10px;">N.S.I : Terminale - 2022 - 2023</span>
                      </header>'
      footerTemplate: '<footer style="position:relative;width:100%;font-size:8px;color:#3B444B;margin:10px 20px;-webkit-print-color-adjust: exact">
                        <span>M.Meyroneinc-Condy | CCBY | 2021</span>
                        <span class="page" style="position:absolute;bottom:0;right:0;">
                         <span class="pageNumber"></span>/<span class="totalPages"></span>
                        </span>'
  #   headerTemplate : 
  #      title
  #      date
  #      pageNumber
  #      totalPages
  #    footerTemplate : True
  #      pageNumber
  #      totalPages
      




extra_javascript:
  - xtra/mathjax.js                    # MathJax
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
