# Fichier de configuration du site à personnaliser

# Informations du site 
site_name: Site NSI Terminale Lycée Murat ISSOIRE
site_description: Cours et TD de l'année en cours
site_author: "Michael Meyroneinc-condy" 
copyright: 2022 sous licence <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr" target="_blank">CC BY-NC-SA 4.0</a> 
site_url: 

# Structure des dossiers :
docs_dir: docs

# Menu de navigation
nav: 
    - Accueil : index.md
    #- Test : Notebook.ipynb
    #Struct. de données
    - T1 - Structure de données :  
      - Les dictionnaires : StructureDonnees/TP07_Dictionnaires_Corrige.md
      - TP 11 - Les Listes : TD11_Les_Listes.md
      - TP 11 - Les Listes Corrigé : TD11_Corrige.md
     # - TP 12 - Liste Chainée : TD12_ListeChainee.md
      - TP 12 - Liste Chainée Enoncé-Corrigé : TD12_ListeChainee_Corrige.md
     # - TP 13 - Les Piles Enoncé-Corrigé : StructureDonnees/TD13_Piles_Corrige.md
      - TP 13 - Les Piles Enoncé-Corrigé : StructureDonnees/TD13_Piles.md
      - TP 14 - Les Files Enoncé-Corrigé : StructureDonnees/TD14_Files.md
      - TP 15 - Les Arbres Enoncé-Corrigé : StructureDonnees/TD15_Les_Arbres.md
    - T2 - Bases de données :  
      - TP 17 - Les JO Londres 2012 : BasesDonnees/TP17_JO.md
      - TD 18 - Sujet BAC 2021 : BasesDonnees/TD18_Revision_SQL_BAC.md
    - T3 - Archi. matèrielle :
      #- TD 19 - Protocole de routage : Reseaux/TD19_Routage.md
      - TD 19 - Protocole de routage : Reseaux/TD19_Routage_Correction.md
      #- TD 16 - Protocole de routage : Reseaux/cours.md
      #- TD 17 : Reseaux/02_Exercices.md
    - T5 Algo. : 
      #- TD 20 : diviserregner/TD20_Diviser_pour_Regner.md
      - TD 20 correction : diviserregner/TD20_Diviser_pour_Regner_Correction.md
    - BAC 📝:
      - TD 21 Exercices BAC : divers/Exercices_Bac.md
      - TD 22 Exercices BAC 2 : divers/Exercice_Bac__2.md
      #- TD 22 Exercices BAC 2 : divers/Exercice_Bac_2_Correction.md
    #- Retour 1ère :
    #  - TD : Revision1ere/TD_Glouton.md
    #BAC 
    - E.P 💻: 
      - Déroulement : epreuve_pratique.md
      - Sujets : divers/EpreuvePratique.md
      #- EP 2022 : BAC/EP_2022.md
  
    #Devoirs
    - Devoirs :
      - P.O.O : DM/DM_POO.md
      - DS 30/11/21 : Devoirs/DS _Listes_Piles_Files.md
      - EP 30/11/21 : Devoirs/DS_EP.md
      #- Révision : StructureDonnees/Revision_Arbres.md
      - DS 14/12/21 : Devoirs/DS_14_12_21_arbres.md
      - DS 14/12/21 - Correction : Devoirs/DS_14_12_21_arbres_Correction.md
      - DS 03/01/22 - Correction : Devoirs/DS_03_01_22_correction.md
      - DS Routage : Devoirs/DS_25_01_22.md
      - DS Routage Correction : Devoirs/DS_25_01_22_Routage_Correction.md


    #- Divers :
      #- TP Perseverance : divers/Perseverance.md
      #- Epreuve GEIPI : divers/sujet0_geipi.pdf
    - Divers conseils : divers/conseil.md
    # Référencer vos autres pages ci-dessus...
    


# Définition du thème https://squidfunk.github.io/mkdocs-material/creating-your-site/
theme:
    name: material
    custom_dir: overrides
    font: false  # RGPD ; pas de fonte Google
    language: fr # français
    icon:
      logo: fontawesome/solid/code

    palette: # Palettes de couleurs jour/nuit, cf : https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
      - scheme: default # nom du thème clair
        primary: lime # couleur primaire des titres, des liens, ..., à prendre dans la liste
        accent: indigo # couleur d'accentuation au survol des boutons, desliens, ..., à prendre dans la liste
        toggle: # définition du bouton pour switcher de palette
          icon: material/weather-sunny # apparence
          name: Basculer en mode sombre # message
      - scheme: slate # nom du thème sombre
        primary: brown
        accent: brown
        toggle:
          icon: material/weather-night
          name: Basculer en mode clair

    features:
        - navigation.instant
        - navigation.tabs
        - navigation.expand
        - navigation.top
        - navigation.sections
        - navigation.indexes
        - navigation.tracking
        - toc.integrate
        - header.autohide
        - content.code.annotate
     


markdown_extensions: # https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
    # extensions de la bibliothèque markdown standard
    - abbr                          # infobulles sur abbréviations 
    - meta                          # Métadonnées
    - def_list                      # Les listes de définition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - md_in_html                    # Pour écrire en MarkDown dans des balises HTML https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorés  !!! info "ma remarque"
    - toc: # Table des matières
        permalink: ⚓︎
        toc_depth: 1
    # extensions de python-markdown https://facelessuser.github.io/pymdown-extensions/
    - pymdownx.details              #   qui peuvent se plier/déplier.
    - pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surligné==.
    - pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
    - pymdownx.highlight            # Coloration syntaxique du code
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed:               # Volets glissants.  === "Mon volet"
        alternate_style: true 
    - pymdownx.superfences          # Imbrication de blocs.
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:               # Émojis  :boom:
        emoji_index:     !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:  # Formules en LaTeX 
        generic: true
    


plugins:
  - search # Inclure une barre de recherche
  - mkdocs-jupyter: # Convertir les fichiers .ipynb et .py en pages du site https://github.com/danielfrg/mkdocs-jupyter
      kernel_name: python3
      execute: False
      include_source: True

  #- page-to-pdf : 
  #    disableOnServe: False
  #    displayHeaderFooter: True
  #    printBackground: True
  #    scale : 1.0
  #    landscape : False
  #    margin: {'top': '0.75cm', 'bottom': '0.75cm', 'right': '0.5cm','left': '0.5cm'}
  #    headerTemplate: '<header style="width:100%;heigth:45px;font-size:10px;font-weight:600;color:white;background:#87A96B;margin-top:-20px;padding:10px;padding-bottom:0;-webkit-print-color-adjust: exact">
  #                      <span style="display:inline-block;vertical-align:middle;margin-top:-4px;margin-left:10px;">N.S.I : Terminale 2021 - 2022</span>
  #                    </header>'
  #    footerTemplate: '<footer style="position:relative;width:100%;font-size:8px;color:#3B444B;margin:10px 20px;-webkit-print-color-adjust: exact">
  #                      <span>M.Meyroneinc-Condy | CCBY | 2021</span>
  #                      <span class="page" style="position:absolute;bottom:0;right:0;">
  #                       <span class="pageNumber"></span>/<span class="totalPages"></span>
  #                      </span>
  #                    </footer>'
  #   headerTemplate : 
  #      title
  #      date
  #      pageNumber
  #      totalPages
  #    footerTemplate : True
  #      pageNumber
  #      totalPages
      


extra:
  social: # A personaliser...
    - icon: fontawesome/solid/paper-plane
      link: mailto:nsi.meyroneinc@gmail.com
      name: Pour toute question, suggestion ou commentaire, écrire à l'auteur

    - icon: fontawesome/brands/github
      link: 
      name: dépôt github

    - icon: fontawesome/solid/university
      link: https://murat-issoire.ent.auvergnerhonealpes.fr/
      name: Lycée Murat Issoire


extra_javascript:
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
