# Fichier de configuration du site à personnaliser

# Informations du site 
site_name: Site NSI Terminale Lycée Murat ISSOIRE
site_description: Cours et TD de l'année en cours
site_author: "Michael Meyroneinc-condy" 
copyright: 2021 sous licence <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr" target="_blank">CC BY-NC-SA 4.0</a> 
site_url: 

# Structure des dossiers :
docs_dir: docs

# Menu de navigation
nav: 
    - Accueil : index.md
    - Les dictionnaires : StructureDonnees/TP07_Dictionnaires_Corrige.md
    #Structure de données
    - Thème n°1 - Structure de données :  
      - TP 11 - Les Listes : TD11_Les_Listes.md
      - TP 11 - Les Listes Corrigé : TD11_Corrige.md
     # - TP 12 - Liste Chainée : TD12_ListeChainee.md
      - TP 12 - Liste Chainée Enoncé-Corrigé : TD12_ListeChainee_Corrige.md
     # - TP 13 - Les Piles Enoncé-Corrigé : StructureDonnees/TD13_Piles_Corrige.md
      - TP 13 - Les Piles Enoncé-Corrigé : StructureDonnees/TD13_Piles.md
      - TP 14 - Les Files Enoncé-Corrigé : StructureDonnees/TD14_Files.md
      #- TP 15 - Les Arbres Enoncé-Corrigé : StructureDonnees/TD15_Les_Arbres.md
    #BAC
    - Epreuves pratiques : 
      - Déroulement : epreuve_pratique.md
      - Sujets : divers/EpreuvePratique.md
    
    #Devoirs
    - Devoirs :
      - P.O.O : DM/DM_POO.md
      #- DS 30/11/21 : Devoirs/DS _Listes_Piles_Files.md
      #- EP 30/11/21 : Devoirs/DS_EP.md

    - Divers conseils : divers/conseil.md
    # Référencer vos autres pages ci-dessus...
    


# Définition du thème https://squidfunk.github.io/mkdocs-material/creating-your-site/
theme:

    name: material
    custom_dir: overrides
    font: false  # RGPD ; pas de fonte Google
    language: fr # français
    icon:
      logo: fontawesome/solid/code

    palette: # Palettes de couleurs jour/nuit, cf : https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
      - scheme: default # nom du thème clair
        primary: teal # couleur primaire des titres, des liens, ..., à prendre dans la liste
        accent: indigo # couleur d'accentuation au survol des boutons, desliens, ..., à prendre dans la liste
        toggle: # définition du bouton pour switcher de palette
          icon: material/weather-sunny # apparence
          name: Basculer en mode sombre # message
      - scheme: slate # nom du thème sombre
        primary: teal
        accent: indigo
        toggle:
          icon: material/weather-night
          name: Basculer en mode clair

    features:
        - navigation.instant
        - navigation.tabs
        - navigation.expand
        - navigation.top
        #- navigation.sections
        #- navigation.indexes
        #- navigation.tracking
        - toc.integrate
        - header.autohide
     


markdown_extensions: # https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
    # extensions de la bibliothèque markdown standard
    - abbr                          # infobulles sur abbréviations 
    - meta                          # Métadonnées
    - def_list                      # Les listes de définition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - md_in_html                    # Pour écrire en MarkDown dans des balises HTML https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorés  !!! info "ma remarque"
    - toc: # Table des matières
        permalink: ⚓︎
        toc_depth: 1
    # extensions de python-markdown https://facelessuser.github.io/pymdown-extensions/
    - pymdownx.details              #   qui peuvent se plier/déplier.
    - pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surligné==.
    - pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
    - pymdownx.highlight            # Coloration syntaxique du code
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed               # Volets glissants.  === "Mon volet"
    - pymdownx.superfences          # Imbrication de blocs.
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:               # Émojis  :boom:
        emoji_index:     !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:  # Formules en LaTeX 
        generic: true
    
  

plugins:
  - search # Inclure une barre de recherche
  - mkdocs-jupyter: # Convertir les fichiers .ipynb et .py en pages du site https://github.com/danielfrg/mkdocs-jupyter
      kernel_name: python3
      execute: False
      include_source: True
  #- mkpdfs:
  #      company: The War Company Inc.
  #      author: Monsieur Silvestre
  #- page-to-pdf : 
  #    disableOnServe : False
  #    scale : 1.0
  #    margin: {'top': '0.5cm', 'bottom': '0.5cm', 'right': '0.5cm','left': '0.5cm'}
  #    headerTemplate : 
  #      title
  #      date
  #      pageNumber
  #      totalPages
  #    footerTemplate : True
  #      pageNumber
  #      totalPages
      


extra:
  social: # A personaliser...
    - icon: fontawesome/solid/paper-plane
      link: mailto:nsi.meyroneinc@gmail.com
      name: Pour toute question, suggestion ou commentaire, écrire à l'auteur

    - icon: fontawesome/brands/github
      link: 
      name: dépôt github

    - icon: fontawesome/solid/university
      link: https://murat-issoire.ent.auvergnerhonealpes.fr/
      name: Lycée Murat Issoire


extra_javascript:
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
